export { Hero } from "./Hero";
export { Stats } from "./Stats";
export { CallToAction } from "./CallToAction";
export { Specialties } from "./Specialties";
export { Team } from "./Team";
export { About } from "./About";
export { Testimonials } from "./Testimonials";
export { FAQ } from "./FAQ";
export { Contact } from "./Contact";
